services:
  rss:
    environment:
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - RSS_BASE_URL=http://localhost:8000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./configs:/config
      - data:/data
volumes:
  data: {}
