on:
  workflow_call:
      inputs:
        storage_handler:
          required: true
          type: string

env:
  IMAGE_NAME: precis
#
jobs:
  # This pushes the image to GitHub Packages.
  integration_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PRECIS_STORAGE: ${{ inputs.storage_handler }}
      CONFIG_DIR: tests/integration/config/
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: |
          pip install uv && uv venv
          source .venv/bin/activate
          make install-ci
      - name: test
        run: |
          source .venv/bin/activate
          precis load-feeds
          make run-ci 2>& 1 > /dev/null
          make test
