name: Integration Test
on:
  workflow_call:
      inputs:
        storage_handler:
          required: true
          type: string
        content_retrieval_handler:
          required: true
          type: string

env:
  IMAGE_NAME: precis
#
jobs:
  integration_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PRECIS_STORAGE_HANDLER: ${{ inputs.storage_handler }}
      CONFIG_DIR: ${{ github.workspace }}/tests/integration/config
      DATA_DIR: ${{ github.workspace }}
      RSS_BASE_URL: http://localhost:8000
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: |
          pip install uv && uv venv
          source .venv/bin/activate
          make install-ci
      - name: test
        run: |
          source .venv/bin/activate
          mv tests/integration/config/${{ inputs.content_retrieval_handler }}.yml tests/integration/config/settings.yml
          precis load-settings
          precis load-feeds
          precis check-feeds
          make run-ci
          make test
